spring.application.name=apijava

# Mongo (usando la URI del entorno)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
