spring.application.name=apijava

# Mongo (URI fija, sin variable de entorno)
# Deja la URI solo con el host y el puerto
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=miappdb

#spring.data.mongodb.connect-timeout=20000
#spring.data.mongodb.socket-timeout=20000
#spring.data.mongodb.retryWrites=true
#spring.data.mongodb.retryReads=true

logging.level.org.springframework.data.mongodb=DEBUG

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:user}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:password}
